### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by dgilperez** [jaxi/elixir-sips-downloader#1]
Hi! 

Quick question: what is it supposed to go in `YOUR_FEED`? 

Thanks!

**Comment by jingkaihe** [comment]
Hey @dgilperez. Glad you use my downloader. The feed would be `https://elixirsips.dpdcart.com/feed`.

**Comment by dgilperez** [comment]
Thanks!

**Comment by jingkaihe** [comment]
To be accurate you need to download the content of `https://elixirsips.dpdcart.com/feed` (let's say saved as `feed.xml`). Then running `go run feed.go feed.xml FOLDER_NAME EMAIL PASSWORD` should work.
